### ISSUE TITLE
Launcher won't start on linux

### ISSUE THREAD

**Issue by LeonardoCT** [modrinth/code#1198]
### Describe the bug

The launcher won't start, i've tryed both the appimage and the deb installation but no luck, in the console it complains about some kind of memory allocation failure. here is the LOG:

**WITHOUT RUST_BACKTRACE=1**
leonardo@leonardo-Lmint:~/Scaricati$ ./modrinth-app_0.7.1_amd64.AppImage 
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

** (modrinth-app:6880): WARNING **: 11:04:03.351: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.2/src/linux.rs:94:49:
Can't create listener: Os { code: 98, kind: AddrInUse, message: "Indirizzo già in uso" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Annullato (core dump creato)

**WITH RUST_BACKTRACE=1**
leonardo@leonardo-Lmint:~/Scaricati$ ./modrinth-app_0.7.1_amd64.AppImage RUST_BACKTRACE=1
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

** (modrinth-app:6978): WARNING **: 11:04:29.083: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.2/src/linux.rs:94:49:
Can't create listener: Os { code: 98, kind: AddrInUse, message: "Indirizzo già in uso" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Annullato (core dump creato)

### Steps to reproduce

1. download the launcher (deb/appimmage)
2. try to start the launcher

### Expected behavior

Being able to start and use the launcher

### System information

OS: Linux Mint 21.3 x86_64 
Kernel: 6.5.0-35-generic 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: Xfce 4.18 
CPU: Intel i5-9400F (6) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 980 
Memory: 32018MiB

**Comment by carterprince** [comment]
Probably duplicate of https://github.com/modrinth/theseus/issues/1186

See my fix [here](https://github.com/modrinth/theseus/issues/1186#issuecomment-2104911642) in that issue.

**Comment by getchoo** [comment]
This is actually a duplicate of https://github.com/modrinth/code/issues/1043. You can see the line in the deep-link plugin that's responsible for this message [here](https://github.com/FabianLars/tauri-plugin-deep-link/blob/1aa5c3d01dfadfe6495673bb8767a913198da279/src/linux.rs#L94). Try removing `/tmp/com.modrinth.theseus-deep-link.sock` and launching the app again

**Comment by Prospector** [comment]
Consolidating into #3057
