### ISSUE TITLE
Modrinth modpacks keep crashing when loading or creating a world

### ISSUE THREAD

**Issue by Yo-Snowpro** [modrinth/code#2136]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

Theseus v0.7.1

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Basically, Whenever I try to create or join a world, it loads then says "Saving World..." then crashes. or in a rare scenerio it thinks its a server and couldn't find the 'server' and puts you to the server screen.

### Steps to reproduce

1. Open any modpack with the modloader fabric.
2. Join or create a world.
3. Crash.

### Expected behavior

Fabric Should boot up, and allow you to join the world.

### Additional context

Crash Log:
[11:52:08] [Render thread/INFO]:
 Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:52:09] [Render thread/WARN]:
 Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:52:09] [Render thread/INFO]:
 Successfully reloaded the world map shaders!
[11:52:09] [Render thread/INFO]:
 reloading ETF data.
[11:52:09] [Render thread/INFO]:
 emissive suffixes loaded: {_e}.
[11:52:13] [Render thread/INFO]:
 Loaded 1437 advancements
[11:52:20] [Render thread/INFO]:
 Applied 65 biome modifications to 52 of 64 new biomes in 14.69 ms
[11:52:20] [Server thread/INFO]:
 Starting integrated minecraft server version 1.21
[11:52:20] [Server thread/INFO]:
 Generating keypair
[11:52:20] [Server thread/INFO]:
 Preparing start region for dimension minecraft:overworld
[11:52:21] [Render thread/INFO]:
 Preparing spawn area: 2%
[11:52:21] [Render thread/INFO]:
 Time elapsed: 174 ms
[11:52:21] [Server thread/INFO]:
 Changing view distance to 12, from 10
[11:52:21] [Server thread/INFO]:
 Changing simulation distance to 12, from 0
[11:52:22] [Server thread/INFO]:
 {MINECRAFT_USERNAME}[local:E:408b5398] logged in with entity id 1 at (-1.5, -60.0, -3.5)
[11:52:22] [Server thread/INFO]:
 {MINECRAFT_USERNAME} joined the game
[11:52:22] [Render thread/INFO]:
 New world map session initialized!
[11:52:22] [Render thread/INFO]:
 Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[11:52:22] [Render thread/INFO]:
 Destroying pipeline minecraft:overworld
[11:52:22] [Render thread/INFO]:
 Creating pipeline for dimension minecraft:overworld
[11:52:22] [Render thread/INFO]:
 Started 2 worker threads
[11:52:22] [Render thread/INFO]:
 Loaded 2 advancements
[11:52:23] [Chunk Render Task Executor #0/ERROR]:
 Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-fa8325fb44abed50.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bni000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
[11:52:23] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-fa8325fb44abed50.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bni000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
[11:52:24] [Server thread/INFO]:
 Stopping server
[11:52:24] [Server thread/INFO]:
 Saving players
[11:52:24] [Server thread/INFO]:
 Saving worlds
[11:52:25] [Server thread/INFO]:
 Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[11:52:26] [Server thread/INFO]:
 Saving chunks for level 'ServerLevel[Test]'/minecraft:the_end
[11:52:26] [Server thread/INFO]:
 Saving chunks for level 'ServerLevel[Test]'/minecraft:the_nether
[11:52:27] [Server thread/INFO]:
 ThreadedAnvilChunkStorage (Test): All chunks are saved
[11:52:27] [Server thread/INFO]:
 ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:52:27] [Server thread/INFO]:
 ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:52:27] [Server thread/INFO]:
 ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by Thinkseal** [comment]
Can you please send the log using [mclo.gs](https://mclo.gs) also most likely this is not a bug with the modrinth app and just a bug with on of the mods you use

**Comment by Yo-Snowpro** [comment]
Link one: https://api.mclo.gs/1/raw/ozZZ7m2
Link two: https://mclo.gs/ozZZ7m2

**Comment by Yo-Snowpro** [comment]
I found out that yetanotherconfiglib caused the crash :/
