### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by srnyx** [modrinth/code#260]
### Describe the bug

I tried launching my instance but it won't work and I get: `I/O error: The system cannot find the path specified. (os error 3)` at `index-cf3e2e2b.js:34`

I also can't go to the Logs page of the instance and my dev console is spammed with this error constantly (while in the Logs page):
```
TypeError: Cannot read properties of undefined (reading 'split')
    at index-cf3e2e2b.js:44:2351
    at r (index-cf3e2e2b.js:1:16949)
    at qe (index-cf3e2e2b.js:1:30045)
    at Proxy.<anonymous> (index-cf3e2e2b.js:5:27907)
    at El (index-cf3e2e2b.js:1:17261)
    at nu.ee [as fn] (index-cf3e2e2b.js:1:45356)
    at nu.run (index-cf3e2e2b.js:1:5504)
    at E.update (index-cf3e2e2b.js:1:46130)
    at pr (index-cf3e2e2b.js:1:14036)
    at bm (index-cf3e2e2b.js:1:15668)
```
When leaving the Logs page, I get these 2 errors:
```
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at index-cf3e2e2b.js:44:1382
    at index-cf3e2e2b.js:1:28794
    at pr (index-cf3e2e2b.js:1:14028)
    at Gt (index-cf3e2e2b.js:1:14107)
    at Ia.t.__weh.t.__weh (index-cf3e2e2b.js:1:28674)
    at Io (index-cf3e2e2b.js:1:1968)
    at Te (index-cf3e2e2b.js:1:49713)
    at _e (index-cf3e2e2b.js:1:48979)
    at Object.unmount (index-cf3e2e2b.js:1:22002)
    at _e (index-cf3e2e2b.js:1:49026)
TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (index-cf3e2e2b.js:1:57622)
    at C (index-cf3e2e2b.js:1:41585)
    at y (index-cf3e2e2b.js:1:41186)
    at nu.ee [as fn] (index-cf3e2e2b.js:1:45388)
    at nu.run (index-cf3e2e2b.js:1:5504)
    at E.update (index-cf3e2e2b.js:1:46130)
    at pr (index-cf3e2e2b.js:1:14036)
    at bm (index-cf3e2e2b.js:1:15668)
```

This is only happening with one of my instances and I don't think I even did anything for it to happen. The instance files are all still there too.
Repairing the instance doesn't do anything either.

### Steps to reproduce

Unfortunately, I've got no idea, if I knew which file was missing though that'd be useful, so maybe the code at the locations of the errors would tell me that.

### Expected behavior

No errors and launching/Logs should work

**Comment by srnyx** [comment]
I'm so silly, I forgot I had switched to Java 20 from Java 19 and forgot to update the Java path in Modrinth's settings.
I'll turn this into a suggestion then to make it more apparent *what* file is missing, especially if it's a Java one.
