### ISSUE TITLE
Java Main

### ISSUE THREAD

**Issue by ZombieLover556** [modrinth/code#304]
### Describe the bug

Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Steps to reproduce

Fresh Install on Windows 11
Installed "The Lost Era Modpack"
Tried to launch fails

### Additional context

Windows 11
Newest install of Java as for it recommended 
error pop-up did show after the installation of the application 
Sodium seems to run fine if I make an instance for it
will keep looking for work around because I kinda dont want to go to curseforge again

**Comment by thesuzerain** [comment]
Thanks for your report and for your patience- is this still happening when you try? 
If you go to your settings, what do your java options say? If you click 'test' on them, does it say success for both of them?

**Comment by Geometrically** [comment]
fixed now
