### ISSUE TITLE
cannot run without sudo

### ISSUE THREAD

**Issue by catvin82** [modrinth/code#981]
### Describe the bug

honestly, i don't think this is a modrinth bug, but i cant run modrinth on my fresh system, so i'm making this bug report.

Modrinth app crashes without super user permission (sudo) in fedora 39

### Steps to reproduce

Download modrinth app from https://modrinth.com/app
Run on fedora 39 fresh install
Realise that the x11 bug hasn't been fixed
Open terminal
Run GDK_BACKEND=x11 ~/path-to-appimage
crashes randomly, unlike on my old install

get error
#thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.1/src/linux.rs:94:49:
Can't create listener: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'GDK_BACKEND=x11 ~/Downloads/mod…' terminated by signal SIGABRT (Abort)#

Run with RUST_BACKTRACE=1GDK_BACKEND=x11 ~/path-to-appimage

get error
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-deep-link-0.1.1/src/linux.rs:94:49:
Can't create listener: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: Job 1, 'RUST_BACKTRACE=1 GDK_BACKEND=x1…' terminated by signal SIGABRT (Abort)
get annoyed and 
run sudo RUST_BACKTRACE=1GDK_BACKEND=x11 ~/path-to-appimage
modrinth app works fine, but thinks my home folder is /root not /home/(name)

### Expected behavior

modrinth app to work with GDK_BACKEND=x11 temp workaround

### System information

Linux, Fedora 39 (Workstation Edition)
Kernel: 6.6.9-200.fc39.x86_64
Shell: fish 3.6.4
Resolution: 1920x1080
DE: GNOME 45.2 (wayland)
Terminal: alacritty
CPU: AMD Ryzen 5 5600G
GPU: AMD ATI Radeon RX 7600 (DP1 plugged into monitor)
Memory: 32GB

only on amd, I assume no drivers further than the ones used in Kernel are needed
fresh install of system, a couple of gnome extentions
is super user (not root in this case)

whoami returns
(user)
sudo whoami returns
root

Modrinth app version 0.6.3
2 drives 
old sata drive with old install that worked but rest of system was buggy
new nvme drive where system is currently installed

RPM Fusion installed
Neofetch installed
Brace Browser installed

tell me if you need any other info

**Comment by catvin82** [comment]
have had one more issue with running with sudo also, soundsystem of mc completely breaks even in vanilla, and basically all other streaming video breaks. Gstreamer codecs are installed btw

**Comment by catvin82** [comment]
> have had one more issue with running with sudo also, soundsystem of mc completely breaks even in vanilla, and basically all other streaming video breaks. Gstreamer codecs are installed btw

Not wifi connection issue, seems to be more mc and not modrinth related
150 down 20 up

**Comment by catvin82** [comment]
still happening
please fix

**Comment by catvin82** [comment]
can't play as intended with this, please fix

**Comment by catvin82** [comment]
still happening. has become so much of an issue, considering switching launchers

**Comment by catvin82** [comment]
still prevelent in 0.7.1

**Comment by catvin82** [comment]
can't believe I haven't said this, but the main issue is pipewire and pulseaudio being broken with root

**Comment by ParadoxLeon** [comment]
I have the same issue. Did you found a fix?

**Comment by ParadoxLeon** [comment]
I found a "workaround".
I had two sound mods installed `sound-physics-remastered-forge-1.20.1-1.4.5.jar` and `AmbientSounds_FORGE_v6.0.5_mc1.20.1.jar` disabling both fixed the problem but that isn't the best solution since I want to play with those mods.

**Comment by Prospector** [comment]
Consolidated into #3057
